"""empty message

Revision ID: 96e3c34b6a7a
Revises:
Create Date: 2023-10-23 00:08:32.046888

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "96e3c34b6a7a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("city_name", sa.String(length=127), nullable=True),
        sa.PrimaryKeyConstraint("city_id"),
        sa.UniqueConstraint("city_name"),
    )
    op.create_table(
        "weather",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city_name", sa.String(length=127), nullable=False),
        sa.Column("temperature", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "atmospheric_pressure", sa.Numeric(precision=6, scale=2), nullable=False
        ),
        sa.Column("wind_speed", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("measurement_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_name"],
            ["cities.city_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather")
    op.drop_table("cities")
    # ### end Alembic commands ###
